version: '3.8'

services:
  postgres-api:
    image: postgres:15
    container_name: postgres-api-container
    restart: always
    environment:
      POSTGRES_USER: admin       # Имя пользователя
      POSTGRES_PASSWORD: secret  # Пароль
      POSTGRES_DB: api           # Название базы данных
    ports:
      - "5432:5432"              # Проброс порта (хост:контейнер)
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Сохранение данных в volume
    networks:
      - api-network

volumes:
  postgres-data:                 # Объем для хранения данных

networks:
  api-network:                   # Сеть для контейнера
