services:
  api:
    container_name: s2s-api
    image: justkuna/evolution-api:2.2.0
    restart: always
    platform: linux/amd64
    ports:
      - 3003:8080
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    env_file:
      - .env
    networks:
      - api-network


volumes:
  evolution_instances:
  evolution_store:

networks:
  api-network:
    name: api-network
    driver: bridge
